version: '3.9'

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/${ECR_API_IMAGE_TAG}

networks:
  mcats:
    driver: bridge
