FROM ghcr.io/osgeo/gdal:ubuntu-small-3.8.0

ARG PLUGIN_FUNCTION=gif_maker.py
ARG PLUGIN_DIR=gif_maker_plugin
ARG CONTAINER_HOME=/plugin

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install rasterio --no-binary rasterio

WORKDIR ${CONTAINER_HOME}

COPY ${PLUGIN_DIR} .
RUN pip3 install -r requirements.txt

COPY ${PLUGIN_FUNCTION} .

# Copy other libraries or not
COPY utils ${CONTAINER_HOME}/utils
